modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="clownpierce_mod"
version="1.0.0"
displayName="ClownPierce Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://legacy.curseforge.com/minecraft/mc-mods/clownpierce/files"
authors="The_WereF0X"

[[dependencies.clownpierce_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




